# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_tweet', models.CharField(max_length=30)),
                ('id_user', models.CharField(max_length=25)),
                ('text', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_usuario', models.CharField(max_length=50)),
                ('screen_name', models.CharField(max_length=25)),
            ],
        ),
    ]
