# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 21:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0002_keyword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='texto',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
