# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 22:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0004_keyword_filtro_bool'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='id_user',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
