# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-11 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0005_auto_20160611_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='nombre_usuario',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
