# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0006_auto_20160611_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tiempo',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
