# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 10:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0007_tweet_tiempo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrapWeb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('desc', models.TextField()),
                ('website', models.URLField(max_length=400)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='sentimiento',
            field=models.DecimalField(decimal_places=5, max_digits=6, null=True),
        ),
    ]
