# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-12 14:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter', '0010_tweet_mina'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tiempo_real',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
